use shopping_analysis;

#what is the total revenue  generated by  male vs female customers
select gender,sum(purchase_amount)  as revenue from customer_shopping
 group by gender;
 
 
# which customer used a discount but still spend more than the average purchase amount 
select customer_id,purchase_amount from customer_shopping 
where discount_applied="yes" and purchase_amount>=(select avg(purchase_amount) from  customer_shopping)


#which are the top 5 products with the highest average review rating
select  item_purchased,  round(avg(review_rating),2)  as average_review_rating  from customer_shopping
group by item_purchased
order by  avg(review_rating) DESC  limit 5;


#compare  the average purchase amounts between standard and express shipping
select round(avg(purchase_amount),2 )as average_purchase_amounts,shipping_type  from customer_shopping
where  shipping_type in('standard', 'express')
group by shipping_type



-- Do  subscribed customers spend more ?
-- compare average spend  with  total revenue between subscriber and non subscriber
select subscription_status ,round(avg(purchase_amount),2) as avg_amount ,sum(purchase_amount) as total_revenue from customer_shopping 
group by subscription_status;

#which 5 products have the highest  percentage of purchases with  discount applied

SELECT 
    item_purchased,
    COUNT(*) AS total_purchases,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) AS discounted_purchases,
    ROUND(
      COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*)
    , 2) AS discount_percentage

FROM customer_shopping
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- segment customers into new,returning ,and loyalbased on their total number of previous purchases ,
-- and show the count of segments
SELECT 
    customer_segment,
    COUNT(customer_id) AS customer_count
FROM (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases <= 1  THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 4 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_shopping
) AS segmented_customers
GROUP BY customer_segment
ORDER BY customer_count DESC;


# Advanced:- what are the top 3 most purchased products within each cateogry
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() OVER (partition by category order by count(customer_id) DESC) as item_rank  from customer_shopping 
group by category,item_purchased
)
select item_rank ,category,item_purchased,total_orders from item_counts
where item_rank<=3
order by category ,item_rank;


#Are customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribed
select subscription_status , count(customer_id)  from customer_shopping 
where previous_purchases>5
group by subscription_status;

#what is the revenue contribution of each age group 
select age_Group, sum(purchase_amount) as revenue from customer_shopping
group by age_Group
order by revenue desc ;
